# Lab 01 - Data Loading: AI Workforce Displacement 2020-2026

This notebook applies **Lab 1 - Installing IDE/Data Loading** to the assignment dataset. The aim is to load the local CSV with pandas and inspect the loaded dataframe before any preprocessing or modelling.

## Lab 1 concepts used

- Confirm the Python data-analysis stack.
- Import pandas.
- Load a local CSV file with `pd.read_csv`.
- Configure dataframe display settings.
- View the loaded dataframe, first rows, last rows, shape, columns, and dtypes.

The Lab 1 Excel and URL examples are not repeated here because this assignment dataset is already available as a local CSV file.

In [1]:
import pandas as pd
from pathlib import Path

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 20)

In [3]:
from pathlib import Path
PROJECT_ROOT = Path.cwd()
while PROJECT_ROOT.name != 'AML Assignment' and PROJECT_ROOT.parent != PROJECT_ROOT:
    PROJECT_ROOT = PROJECT_ROOT.parent
PROJECT_ROOT

WindowsPath('D:/APU Study/1st Semester/Applied Machine Learning/AML Assignment')

In [4]:
DATASET_FILENAME = 'ai_workforce_displacement_global_2020_2026.csv'
matches = sorted((PROJECT_ROOT / 'Datasets').glob(f'*/{DATASET_FILENAME}'))
if not matches:
    raise FileNotFoundError(f'Could not find {DATASET_FILENAME} under {PROJECT_ROOT / "Datasets"}')
DATASET_PATH = matches[0]
print(DATASET_PATH)
print('File exists:', DATASET_PATH.exists())

D:\APU Study\1st Semester\Applied Machine Learning\AML Assignment\Datasets\AI Workforce Displacement 2020–2026\ai_workforce_displacement_global_2020_2026.csv
File exists: True

In [5]:
data = pd.read_csv(DATASET_PATH)
data

,record_id,country,iso3_code,region,income_group,year,quarter,quarter_label,industry_sector,sector_automation_risk_score,gdp_per_capita_usd,ai_adoption_index,pct_sector_workforce_displaced,pct_sector_workforce_new_roles_created,net_workforce_change_pct,ai_cited_layoff_announcements,ai_skill_wage_premium_pct,pct_workforce_female,pct_displaced_roles_female,reskilling_programs_count,govt_ai_policy_score_1_to_10,ai_tool_adoption_pct,data_source_notes
0,1,United States,USA,North America,High Income,2020,1,2020-Q1,Technology & Software,0.382,63514,0.830,0.0406,0.0348,-0.0058,32,0.311,0.28,0.275,52,6.4,0.280,Research-calibrated synthetic data. Grounded i...
1,2,United States,USA,North America,High Income,2020,1,2020-Q1,Finance & Banking,0.608,63514,0.817,0.0517,0.0423,-0.0094,51,0.304,0.48,0.511,39,6.5,0.559,Research-calibrated synthetic data. Grounded i...
2,3,United States,USA,North America,High Income,2020,1,2020-Q1,Healthcare & Life Sciences,0.198,63514,0.816,0.0176,0.0168,-0.0008,4,0.278,0.72,0.707,37,6.8,0.202,Research-calibrated synthetic data. Grounded i...
3,4,United States,USA,North America,High Income,2020,1,2020-Q1,Manufacturing & Industry,0.720,63514,0.818,0.0924,0.0642,-0.0282,47,0.268,0.29,0.310,50,6.8,0.655,Research-calibrated synthetic data. Grounded i...
4,5,United States,USA,North America,High Income,2020,1,2020-Q1,Retail & E-Commerce,0.676,63514,0.828,0.0667,0.0374,-0.0293,31,0.313,0.54,0.547,37,6.2,0.542,Research-calibrated synthetic data. Grounded i...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20795,20796,Zambia,ZMB,Africa,Lower Middle Income,2026,2,2026-Q2,Education & Research,0.308,1467,0.703,0.0218,0.0056,-0.0162,29,0.450,0.58,0.651,16,3.5,0.184,Research-calibrated synthetic data. Grounded i...
20796,20797,Zambia,ZMB,Africa,Lower Middle Income,2026,2,2026-Q2,Transportation & Logistics,0.675,1467,0.711,0.0534,0.0205,-0.0329,126,0.476,0.22,0.235,15,4.2,0.457,Research-calibrated synthetic data. Grounded i...
20797,20798,Zambia,ZMB,Africa,Lower Middle Income,2026,2,2026-Q2,Media & Communications,0.516,1467,0.709,0.0505,0.0154,-0.0351,131,0.446,0.46,0.482,17,4.3,0.419,Research-calibrated synthetic data. Grounded i...
20798,20799,Zambia,ZMB,Africa,Lower Middle Income,2026,2,2026-Q2,Administrative & Clerical,0.801,1467,0.702,0.0914,0.0260,-0.0654,476,0.499,0.79,0.950,14,4.2,0.459,Research-calibrated synthetic data. Grounded i...
20799,20800,Zambia,ZMB,Africa,Lower Middle Income,2026,2,2026-Q2,Energy & Utilities,0.440,1467,0.718,0.0376,0.0160,-0.0216,67,0.490,0.26,0.270,12,4.1,0.377,Research-calibrated synthetic data. Grounded i...

In [6]:
data.head()

,record_id,country,iso3_code,region,income_group,year,quarter,quarter_label,industry_sector,sector_automation_risk_score,gdp_per_capita_usd,ai_adoption_index,pct_sector_workforce_displaced,pct_sector_workforce_new_roles_created,net_workforce_change_pct,ai_cited_layoff_announcements,ai_skill_wage_premium_pct,pct_workforce_female,pct_displaced_roles_female,reskilling_programs_count,govt_ai_policy_score_1_to_10,ai_tool_adoption_pct,data_source_notes
0,1,United States,USA,North America,High Income,2020,1,2020-Q1,Technology & Software,0.382,63514,0.830,0.0406,0.0348,-0.0058,32,0.311,0.28,0.275,52,6.4,0.280,Research-calibrated synthetic data. Grounded i...
1,2,United States,USA,North America,High Income,2020,1,2020-Q1,Finance & Banking,0.608,63514,0.817,0.0517,0.0423,-0.0094,51,0.304,0.48,0.511,39,6.5,0.559,Research-calibrated synthetic data. Grounded i...
2,3,United States,USA,North America,High Income,2020,1,2020-Q1,Healthcare & Life Sciences,0.198,63514,0.816,0.0176,0.0168,-0.0008,4,0.278,0.72,0.707,37,6.8,0.202,Research-calibrated synthetic data. Grounded i...
3,4,United States,USA,North America,High Income,2020,1,2020-Q1,Manufacturing & Industry,0.720,63514,0.818,0.0924,0.0642,-0.0282,47,0.268,0.29,0.310,50,6.8,0.655,Research-calibrated synthetic data. Grounded i...
4,5,United States,USA,North America,High Income,2020,1,2020-Q1,Retail & E-Commerce,0.676,63514,0.828,0.0667,0.0374,-0.0293,31,0.313,0.54,0.547,37,6.2,0.542,Research-calibrated synthetic data. Grounded i...

In [7]:
data.tail()

,record_id,country,iso3_code,region,income_group,year,quarter,quarter_label,industry_sector,sector_automation_risk_score,gdp_per_capita_usd,ai_adoption_index,pct_sector_workforce_displaced,pct_sector_workforce_new_roles_created,net_workforce_change_pct,ai_cited_layoff_announcements,ai_skill_wage_premium_pct,pct_workforce_female,pct_displaced_roles_female,reskilling_programs_count,govt_ai_policy_score_1_to_10,ai_tool_adoption_pct,data_source_notes
20795,20796,Zambia,ZMB,Africa,Lower Middle Income,2026,2,2026-Q2,Education & Research,0.308,1467,0.703,0.0218,0.0056,-0.0162,29,0.450,0.58,0.651,16,3.5,0.184,Research-calibrated synthetic data. Grounded i...
20796,20797,Zambia,ZMB,Africa,Lower Middle Income,2026,2,2026-Q2,Transportation & Logistics,0.675,1467,0.711,0.0534,0.0205,-0.0329,126,0.476,0.22,0.235,15,4.2,0.457,Research-calibrated synthetic data. Grounded i...
20797,20798,Zambia,ZMB,Africa,Lower Middle Income,2026,2,2026-Q2,Media & Communications,0.516,1467,0.709,0.0505,0.0154,-0.0351,131,0.446,0.46,0.482,17,4.3,0.419,Research-calibrated synthetic data. Grounded i...
20798,20799,Zambia,ZMB,Africa,Lower Middle Income,2026,2,2026-Q2,Administrative & Clerical,0.801,1467,0.702,0.0914,0.0260,-0.0654,476,0.499,0.79,0.950,14,4.2,0.459,Research-calibrated synthetic data. Grounded i...
20799,20800,Zambia,ZMB,Africa,Lower Middle Income,2026,2,2026-Q2,Energy & Utilities,0.440,1467,0.718,0.0376,0.0160,-0.0216,67,0.490,0.26,0.270,12,4.1,0.377,Research-calibrated synthetic data. Grounded i...

In [8]:
data.shape

(20800, 23)

In [9]:
list(data.columns)

['record_id',
 'country',
 'iso3_code',
 'region',
 'income_group',
 'year',
 'quarter',
 'quarter_label',
 'industry_sector',
 'sector_automation_risk_score',
 'gdp_per_capita_usd',
 'ai_adoption_index',
 'pct_sector_workforce_displaced',
 'pct_sector_workforce_new_roles_created',
 'net_workforce_change_pct',
 'ai_cited_layoff_announcements',
 'ai_skill_wage_premium_pct',
 'pct_workforce_female',
 'pct_displaced_roles_female',
 'reskilling_programs_count',
 'govt_ai_policy_score_1_to_10',
 'ai_tool_adoption_pct',
 'data_source_notes']

In [10]:
data.dtypes

record_id                         int64
country                             str
iso3_code                           str
region                              str
income_group                        str
                                 ...
pct_displaced_roles_female      float64
reskilling_programs_count         int64
govt_ai_policy_score_1_to_10    float64
ai_tool_adoption_pct            float64
data_source_notes                   str
Length: 23, dtype: object

## What was learned from Lab 1

The dataset was loaded from `Datasets/AI Workforce Displacement 2020?2026/ai_workforce_displacement_global_2020_2026.csv` using pandas. At this stage we only confirm that the file can be read and that the dataframe structure is visible. Data cleaning, preprocessing, and modelling are intentionally left for later labs.