# Lab 01 - Data Loading: LLM Hallucination

This notebook applies **Lab 1 - Installing IDE/Data Loading** to the assignment dataset. The aim is to load the local CSV with pandas and inspect the loaded dataframe before any preprocessing or modelling.

## Lab 1 concepts used

- Confirm the Python data-analysis stack.
- Import pandas.
- Load a local CSV file with `pd.read_csv`.
- Configure dataframe display settings.
- View the loaded dataframe, first rows, last rows, shape, columns, and dtypes.

The Lab 1 Excel and URL examples are not repeated here because this assignment dataset is already available as a local CSV file.

In [1]:
import pandas as pd
from pathlib import Path

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 20)

In [3]:
from pathlib import Path
PROJECT_ROOT = Path.cwd()
while PROJECT_ROOT.name != 'AML Assignment' and PROJECT_ROOT.parent != PROJECT_ROOT:
    PROJECT_ROOT = PROJECT_ROOT.parent
PROJECT_ROOT

WindowsPath('D:/APU Study/1st Semester/Applied Machine Learning/AML Assignment')

In [4]:
DATASET_FILENAME = 'llm_hallucination_dataset_v1.csv'
matches = sorted((PROJECT_ROOT / 'Datasets').glob(f'*/{DATASET_FILENAME}'))
if not matches:
    raise FileNotFoundError(f'Could not find {DATASET_FILENAME} under {PROJECT_ROOT / "Datasets"}')
DATASET_PATH = matches[0]
print(DATASET_PATH)
print('File exists:', DATASET_PATH.exists())

D:\APU Study\1st Semester\Applied Machine Learning\AML Assignment\Datasets\LLM Hallucination\llm_hallucination_dataset_v1.csv
File exists: True

In [5]:
data = pd.read_csv(DATASET_PATH)
data

,record_id,created_date,model_name,model_version,prompt_id,prompt_text,prompt_type,response_text,domain,task_type,language,hallucination_label,hallucination_type,hallucination_span,correct_information,correction_text,severity,domain_risk,annotator_type,annotation_confidence,mitigation_strategy,mitigation_applied,verified_source,intrinsic_or_extrinsic,notes
0,70b69889-3b46-4b1e-8f83-b95720bddbcd,2024-11-02,GPT-4o,gpt-4o-2024-11-20,PROMPT_00001,Who invented the telephone?,Multi-Hop,The telephone was invented by Nikola Tesla in ...,History,Question-Answering,English,1,Entity-Error,Nikola Tesla,Alexander Graham Bell,The telephone was invented by Alexander Graham...,High,Low-Stakes,human_expert,0.73,RAG,True,PubMed,Extrinsic,NaN
1,e93f6574-d3a1-4459-9ccc-8615bc2b627f,2024-09-24,Mistral-Large,mistral-large-2411,PROMPT_00002,What is the boiling point of water at sea level?,Multi-Hop,Water boils at 100 degrees Celsius (212 degree...,Science,Question-Answering,English,0,NaN,NaN,NaN,NaN,NaN,Low-Stakes,human_expert,0.88,NaN,False,ArXiv,NaN,NaN
2,fc732394-9369-4811-8484-e07f69cb6fab,2025-01-29,Mistral-Large,mistral-large-2411,PROMPT_00003,What is the recommended first-line treatment f...,Ambiguous,The first-line pharmacological treatment for T...,Medicine,Question-Answering,Spanish,1,Factual-Contradiction,"insulin therapy, which should be initiated at ...",Metformin is the standard first-line drug,Metformin is the recommended first-line pharma...,High,High-Stakes,human_expert,0.83,Self-Consistency,True,SEC-Filing,Extrinsic,NaN
3,2e488a3d-bfc4-4d1e-b59b-eeca571c9c27,2024-10-26,Llama-3.1-70B,llama-3.1-70b-instruct,PROMPT_00004,When was Apple Inc. founded?,Ambiguous,"Apple Inc. was founded on April 1, 1976, by St...",Finance,Question-Answering,English,0,NaN,NaN,NaN,NaN,NaN,Low-Stakes,human_crowd,0.86,CoT-Prompting,True,PubMed,NaN,NaN
4,eb1c2d1e-9fb6-46f0-9f65-0f36494db9dc,2024-11-07,Gemini-1.5-Pro,gemini-1.5-pro-002,PROMPT_00005,Is it legal to record a phone call without con...,Direct-Factual,"In California, you can legally record a phone ...",Law,Fact-Verification,French,1,Factual-Contradiction,one party to the call consents,California requires all-party consent under Pe...,California is an all-party consent state; all ...,High,High-Stakes,human_expert,0.95,Structured-Prompt,True,Snopes,Extrinsic,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,dc1ddb29-e3d9-4651-a570-c7439d420f95,2025-04-03,GPT-4o,gpt-4o-2024-11-20,PROMPT_00196,When did the Soviet Union collapse?,Ambiguous,The Soviet Union officially dissolved on Decem...,History,Dialogue,Spanish,1,Incompleteness,"officially dissolved on December 25, 1991","Formal dissolution was December 26, 1991 when ...","Gorbachev resigned on December 25, 1991, but t...",Low,Low-Stakes,llm_judge_gpt4o,0.81,NaN,False,Wikipedia,Intrinsic,NaN
196,7f2a8697-2deb-4a69-8a08-3802e53886f8,2025-02-26,Gemini-1.5-Pro,gemini-1.5-pro-002,PROMPT_00197,Summarize what a hedge fund does.,Multi-Hop,A hedge fund is a pooled investment vehicle th...,Finance,Summarization,Hindi,1,Factual-Contradiction,All hedge funds are required to be registered ...,Many hedge funds are exempt from SEC registrat...,Not all hedge funds are required to register w...,Medium,High-Stakes,human_crowd,0.97,Self-Consistency,True,Human-Expert,Extrinsic,NaN
197,c59849f3-99b3-4646-b8c4-9a7904e24e3b,2024-09-05,Mistral-Large,mistral-large-2411,PROMPT_00198,Can you explain what an API is?,Ambiguous,An API (Application Programming Interface) is ...,Technology,Dialogue,English,0,NaN,NaN,NaN,NaN,NaN,Low-Stakes,llm_judge_gpt4o,0.80,NaN,False,Snopes,NaN,NaN
198,a04df3dd-4a1f-4ef8-8d58-04ab3685903d,2024-11-17,GPT-4o,gpt-4o-2024-11-20,PROMPT_00199,Does the MMR vaccine cause autism?,Direct-Factual,No. The claim that the MMR vaccine causes auti...,Medicine,Fact-Verification,English,0,NaN,NaN,NaN,NaN,NaN,High-Stakes,human_crowd,0.95,CoT-Prompting,True,Human-Expert,NaN,NaN
199,6067be34-d199-4995-a770-cc3501f96725,2025-01-31,GPT-4o,gpt-4o-2024-11-20,PROMPT_00200,What is the chemical formula for table salt?,Long-Context,The chemical formula for table salt is NaCl (s...,General,Question-Answering,English,0,NaN,NaN,NaN,NaN,NaN,Low-Stakes,llm_judge_gpt4o,0.82,Self-Consistency,True,SEC-Filing,NaN,NaN

In [6]:
data.head()

,record_id,created_date,model_name,model_version,prompt_id,prompt_text,prompt_type,response_text,domain,task_type,language,hallucination_label,hallucination_type,hallucination_span,correct_information,correction_text,severity,domain_risk,annotator_type,annotation_confidence,mitigation_strategy,mitigation_applied,verified_source,intrinsic_or_extrinsic,notes
0,70b69889-3b46-4b1e-8f83-b95720bddbcd,2024-11-02,GPT-4o,gpt-4o-2024-11-20,PROMPT_00001,Who invented the telephone?,Multi-Hop,The telephone was invented by Nikola Tesla in ...,History,Question-Answering,English,1,Entity-Error,Nikola Tesla,Alexander Graham Bell,The telephone was invented by Alexander Graham...,High,Low-Stakes,human_expert,0.73,RAG,True,PubMed,Extrinsic,NaN
1,e93f6574-d3a1-4459-9ccc-8615bc2b627f,2024-09-24,Mistral-Large,mistral-large-2411,PROMPT_00002,What is the boiling point of water at sea level?,Multi-Hop,Water boils at 100 degrees Celsius (212 degree...,Science,Question-Answering,English,0,NaN,NaN,NaN,NaN,NaN,Low-Stakes,human_expert,0.88,NaN,False,ArXiv,NaN,NaN
2,fc732394-9369-4811-8484-e07f69cb6fab,2025-01-29,Mistral-Large,mistral-large-2411,PROMPT_00003,What is the recommended first-line treatment f...,Ambiguous,The first-line pharmacological treatment for T...,Medicine,Question-Answering,Spanish,1,Factual-Contradiction,"insulin therapy, which should be initiated at ...",Metformin is the standard first-line drug,Metformin is the recommended first-line pharma...,High,High-Stakes,human_expert,0.83,Self-Consistency,True,SEC-Filing,Extrinsic,NaN
3,2e488a3d-bfc4-4d1e-b59b-eeca571c9c27,2024-10-26,Llama-3.1-70B,llama-3.1-70b-instruct,PROMPT_00004,When was Apple Inc. founded?,Ambiguous,"Apple Inc. was founded on April 1, 1976, by St...",Finance,Question-Answering,English,0,NaN,NaN,NaN,NaN,NaN,Low-Stakes,human_crowd,0.86,CoT-Prompting,True,PubMed,NaN,NaN
4,eb1c2d1e-9fb6-46f0-9f65-0f36494db9dc,2024-11-07,Gemini-1.5-Pro,gemini-1.5-pro-002,PROMPT_00005,Is it legal to record a phone call without con...,Direct-Factual,"In California, you can legally record a phone ...",Law,Fact-Verification,French,1,Factual-Contradiction,one party to the call consents,California requires all-party consent under Pe...,California is an all-party consent state; all ...,High,High-Stakes,human_expert,0.95,Structured-Prompt,True,Snopes,Extrinsic,NaN

In [7]:
data.tail()

,record_id,created_date,model_name,model_version,prompt_id,prompt_text,prompt_type,response_text,domain,task_type,language,hallucination_label,hallucination_type,hallucination_span,correct_information,correction_text,severity,domain_risk,annotator_type,annotation_confidence,mitigation_strategy,mitigation_applied,verified_source,intrinsic_or_extrinsic,notes
195,dc1ddb29-e3d9-4651-a570-c7439d420f95,2025-04-03,GPT-4o,gpt-4o-2024-11-20,PROMPT_00196,When did the Soviet Union collapse?,Ambiguous,The Soviet Union officially dissolved on Decem...,History,Dialogue,Spanish,1,Incompleteness,"officially dissolved on December 25, 1991","Formal dissolution was December 26, 1991 when ...","Gorbachev resigned on December 25, 1991, but t...",Low,Low-Stakes,llm_judge_gpt4o,0.81,NaN,False,Wikipedia,Intrinsic,NaN
196,7f2a8697-2deb-4a69-8a08-3802e53886f8,2025-02-26,Gemini-1.5-Pro,gemini-1.5-pro-002,PROMPT_00197,Summarize what a hedge fund does.,Multi-Hop,A hedge fund is a pooled investment vehicle th...,Finance,Summarization,Hindi,1,Factual-Contradiction,All hedge funds are required to be registered ...,Many hedge funds are exempt from SEC registrat...,Not all hedge funds are required to register w...,Medium,High-Stakes,human_crowd,0.97,Self-Consistency,True,Human-Expert,Extrinsic,NaN
197,c59849f3-99b3-4646-b8c4-9a7904e24e3b,2024-09-05,Mistral-Large,mistral-large-2411,PROMPT_00198,Can you explain what an API is?,Ambiguous,An API (Application Programming Interface) is ...,Technology,Dialogue,English,0,NaN,NaN,NaN,NaN,NaN,Low-Stakes,llm_judge_gpt4o,0.80,NaN,False,Snopes,NaN,NaN
198,a04df3dd-4a1f-4ef8-8d58-04ab3685903d,2024-11-17,GPT-4o,gpt-4o-2024-11-20,PROMPT_00199,Does the MMR vaccine cause autism?,Direct-Factual,No. The claim that the MMR vaccine causes auti...,Medicine,Fact-Verification,English,0,NaN,NaN,NaN,NaN,NaN,High-Stakes,human_crowd,0.95,CoT-Prompting,True,Human-Expert,NaN,NaN
199,6067be34-d199-4995-a770-cc3501f96725,2025-01-31,GPT-4o,gpt-4o-2024-11-20,PROMPT_00200,What is the chemical formula for table salt?,Long-Context,The chemical formula for table salt is NaCl (s...,General,Question-Answering,English,0,NaN,NaN,NaN,NaN,NaN,Low-Stakes,llm_judge_gpt4o,0.82,Self-Consistency,True,SEC-Filing,NaN,NaN

In [8]:
data.shape

(200, 25)

In [9]:
list(data.columns)

['record_id',
 'created_date',
 'model_name',
 'model_version',
 'prompt_id',
 'prompt_text',
 'prompt_type',
 'response_text',
 'domain',
 'task_type',
 'language',
 'hallucination_label',
 'hallucination_type',
 'hallucination_span',
 'correct_information',
 'correction_text',
 'severity',
 'domain_risk',
 'annotator_type',
 'annotation_confidence',
 'mitigation_strategy',
 'mitigation_applied',
 'verified_source',
 'intrinsic_or_extrinsic',
 'notes']

In [10]:
data.dtypes

record_id                     str
created_date                  str
model_name                    str
model_version                 str
prompt_id                     str
                           ...
mitigation_strategy           str
mitigation_applied           bool
verified_source               str
intrinsic_or_extrinsic        str
notes                     float64
Length: 25, dtype: object

## What was learned from Lab 1

The dataset was loaded from `Datasets/LLM Hallucination/llm_hallucination_dataset_v1.csv` using pandas. At this stage we only confirm that the file can be read and that the dataframe structure is visible. Data cleaning, preprocessing, and modelling are intentionally left for later labs.