# Lab 01 - Data Loading: Student AI Tools vs Exam Scores

This notebook applies **Lab 1 - Installing IDE/Data Loading** to the assignment dataset. The aim is to load the local CSV with pandas and inspect the loaded dataframe before any preprocessing or modelling.

## Lab 1 concepts used

- Confirm the Python data-analysis stack.
- Import pandas.
- Load a local CSV file with `pd.read_csv`.
- Configure dataframe display settings.
- View the loaded dataframe, first rows, last rows, shape, columns, and dtypes.

The Lab 1 Excel and URL examples are not repeated here because this assignment dataset is already available as a local CSV file.

In [1]:
import pandas as pd
from pathlib import Path

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 20)

In [3]:
from pathlib import Path
PROJECT_ROOT = Path.cwd()
while PROJECT_ROOT.name != 'AML Assignment' and PROJECT_ROOT.parent != PROJECT_ROOT:
    PROJECT_ROOT = PROJECT_ROOT.parent
PROJECT_ROOT

WindowsPath('D:/APU Study/1st Semester/Applied Machine Learning/AML Assignment')

In [4]:
DATASET_FILENAME = 'students_ai_usage.csv'
matches = sorted((PROJECT_ROOT / 'Datasets').glob(f'*/{DATASET_FILENAME}'))
if not matches:
    raise FileNotFoundError(f'Could not find {DATASET_FILENAME} under {PROJECT_ROOT / "Datasets"}')
DATASET_PATH = matches[0]
print(DATASET_PATH)
print('File exists:', DATASET_PATH.exists())

D:\APU Study\1st Semester\Applied Machine Learning\AML Assignment\Datasets\Student AI Tools vs Exam scores\students_ai_usage.csv
File exists: True

In [5]:
data = pd.read_csv(DATASET_PATH)
data

,age,education_level,study_hours_per_day,uses_ai,ai_tools_used,purpose_of_ai,grades_before_ai,grades_after_ai,daily_screen_time_hours
0,19,college,1.4,No,NaN,NaN,62,62,3
1,15,school,3.9,Yes,Copilot,Research,56,61,2
2,15,school,1.9,Yes,Copilot,Homework,75,88,5
3,15,school,2.8,No,NaN,NaN,55,55,3
4,19,college,2.7,No,NaN,NaN,59,59,3
...,...,...,...,...,...,...,...,...,...
95,14,school,4.4,No,NaN,NaN,70,70,2
96,16,school,2.2,No,NaN,NaN,68,68,6
97,19,college,3.9,Yes,Gemini,Homework,63,74,5
98,14,school,2.6,No,NaN,NaN,60,60,5
99,15,school,4.9,Yes,Gemini,Coding,73,88,2

In [6]:
data.head()

,age,education_level,study_hours_per_day,uses_ai,ai_tools_used,purpose_of_ai,grades_before_ai,grades_after_ai,daily_screen_time_hours
0,19,college,1.4,No,NaN,NaN,62,62,3
1,15,school,3.9,Yes,Copilot,Research,56,61,2
2,15,school,1.9,Yes,Copilot,Homework,75,88,5
3,15,school,2.8,No,NaN,NaN,55,55,3
4,19,college,2.7,No,NaN,NaN,59,59,3

In [7]:
data.tail()

,age,education_level,study_hours_per_day,uses_ai,ai_tools_used,purpose_of_ai,grades_before_ai,grades_after_ai,daily_screen_time_hours
95,14,school,4.4,No,NaN,NaN,70,70,2
96,16,school,2.2,No,NaN,NaN,68,68,6
97,19,college,3.9,Yes,Gemini,Homework,63,74,5
98,14,school,2.6,No,NaN,NaN,60,60,5
99,15,school,4.9,Yes,Gemini,Coding,73,88,2

In [8]:
data.shape

(100, 9)

In [9]:
list(data.columns)

['age',
 'education_level',
 'study_hours_per_day',
 'uses_ai',
 'ai_tools_used',
 'purpose_of_ai',
 'grades_before_ai',
 'grades_after_ai',
 'daily_screen_time_hours']

In [10]:
data.dtypes

age                          int64
education_level                str
study_hours_per_day        float64
uses_ai                        str
ai_tools_used                  str
purpose_of_ai                  str
grades_before_ai             int64
grades_after_ai              int64
daily_screen_time_hours      int64
dtype: object

## What was learned from Lab 1

The dataset was loaded from `Datasets/Student AI Tools vs Exam scores/students_ai_usage.csv` using pandas. At this stage we only confirm that the file can be read and that the dataframe structure is visible. Data cleaning, preprocessing, and modelling are intentionally left for later labs.