# Lab 01 - Data Loading: Global Urban Air Quality and Pollution Time-Series

This notebook applies **Lab 1 - Installing IDE/Data Loading** to the assignment dataset. The aim is to load the local CSV with pandas and inspect the loaded dataframe before any preprocessing or modelling.

## Lab 1 concepts used

- Confirm the Python data-analysis stack.
- Import pandas.
- Load a local CSV file with `pd.read_csv`.
- Configure dataframe display settings.
- View the loaded dataframe, first rows, last rows, shape, columns, and dtypes.

The Lab 1 Excel and URL examples are not repeated here because this assignment dataset is already available as a local CSV file.

In [1]:
import pandas as pd
from pathlib import Path

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 20)

In [3]:
from pathlib import Path
PROJECT_ROOT = Path.cwd()
while PROJECT_ROOT.name != 'AML Assignment' and PROJECT_ROOT.parent != PROJECT_ROOT:
    PROJECT_ROOT = PROJECT_ROOT.parent
PROJECT_ROOT

WindowsPath('D:/APU Study/1st Semester/Applied Machine Learning/AML Assignment')

In [4]:
DATASET_FILENAME = 'global_urban_smog_pm25_hourly.csv'
matches = sorted((PROJECT_ROOT / 'Datasets').glob(f'*/{DATASET_FILENAME}'))
if not matches:
    raise FileNotFoundError(f'Could not find {DATASET_FILENAME} under {PROJECT_ROOT / "Datasets"}')
DATASET_PATH = matches[0]
print(DATASET_PATH)
print('File exists:', DATASET_PATH.exists())

D:\APU Study\1st Semester\Applied Machine Learning\AML Assignment\Datasets\Global Urban Air Quality & Pollution Time-Series\global_urban_smog_pm25_hourly.csv
File exists: True

In [5]:
data = pd.read_csv(DATASET_PATH)
data

,Timestamp,City,Latitude,Longitude,PM10_ug_m3,PM2_5_ug_m3,Carbon_Monoxide_ug_m3,Nitrogen_Dioxide_ug_m3,Ozone_ug_m3,Dust_ug_m3,UV_Index,European_AQI,Hazardous_Event
0,2025-05-22T00:00,Lahore,31.5204,74.3587,186.7,74.3,926.0,22.9,94.0,197.0,0.0,76,0
1,2025-05-22T01:00,Lahore,31.5204,74.3587,286.8,96.4,736.0,18.1,103.0,356.0,0.0,77,0
2,2025-05-22T02:00,Lahore,31.5204,74.3587,380.0,122.0,599.0,14.1,110.0,506.0,0.0,78,0
3,2025-05-22T03:00,Lahore,31.5204,74.3587,486.2,149.9,548.0,11.7,114.0,640.0,0.0,80,0
4,2025-05-22T04:00,Lahore,31.5204,74.3587,581.1,172.8,550.0,10.1,118.0,765.0,0.0,85,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
254731,2026-05-22T19:00,Buenos Aires,-34.6037,-58.3816,19.0,15.3,215.0,36.1,15.0,0.0,0.0,31,0
254732,2026-05-22T20:00,Buenos Aires,-34.6037,-58.3816,19.5,15.8,201.0,40.1,11.0,0.0,0.0,30,0
254733,2026-05-22T21:00,Buenos Aires,-34.6037,-58.3816,19.7,15.9,181.0,41.6,9.0,0.0,0.0,29,0
254734,2026-05-22T22:00,Buenos Aires,-34.6037,-58.3816,19.4,15.5,151.0,39.1,10.0,0.0,0.0,29,0
254735,2026-05-22T23:00,Buenos Aires,-34.6037,-58.3816,18.8,15.0,114.0,34.0,14.0,0.0,0.0,28,0

In [6]:
data.head()

,Timestamp,City,Latitude,Longitude,PM10_ug_m3,PM2_5_ug_m3,Carbon_Monoxide_ug_m3,Nitrogen_Dioxide_ug_m3,Ozone_ug_m3,Dust_ug_m3,UV_Index,European_AQI,Hazardous_Event
0,2025-05-22T00:00,Lahore,31.5204,74.3587,186.7,74.3,926.0,22.9,94.0,197.0,0.0,76,0
1,2025-05-22T01:00,Lahore,31.5204,74.3587,286.8,96.4,736.0,18.1,103.0,356.0,0.0,77,0
2,2025-05-22T02:00,Lahore,31.5204,74.3587,380.0,122.0,599.0,14.1,110.0,506.0,0.0,78,0
3,2025-05-22T03:00,Lahore,31.5204,74.3587,486.2,149.9,548.0,11.7,114.0,640.0,0.0,80,0
4,2025-05-22T04:00,Lahore,31.5204,74.3587,581.1,172.8,550.0,10.1,118.0,765.0,0.0,85,0

In [7]:
data.tail()

,Timestamp,City,Latitude,Longitude,PM10_ug_m3,PM2_5_ug_m3,Carbon_Monoxide_ug_m3,Nitrogen_Dioxide_ug_m3,Ozone_ug_m3,Dust_ug_m3,UV_Index,European_AQI,Hazardous_Event
254731,2026-05-22T19:00,Buenos Aires,-34.6037,-58.3816,19.0,15.3,215.0,36.1,15.0,0.0,0.0,31,0
254732,2026-05-22T20:00,Buenos Aires,-34.6037,-58.3816,19.5,15.8,201.0,40.1,11.0,0.0,0.0,30,0
254733,2026-05-22T21:00,Buenos Aires,-34.6037,-58.3816,19.7,15.9,181.0,41.6,9.0,0.0,0.0,29,0
254734,2026-05-22T22:00,Buenos Aires,-34.6037,-58.3816,19.4,15.5,151.0,39.1,10.0,0.0,0.0,29,0
254735,2026-05-22T23:00,Buenos Aires,-34.6037,-58.3816,18.8,15.0,114.0,34.0,14.0,0.0,0.0,28,0

In [8]:
data.shape

(254736, 13)

In [9]:
list(data.columns)

['Timestamp',
 'City',
 'Latitude',
 'Longitude',
 'PM10_ug_m3',
 'PM2_5_ug_m3',
 'Carbon_Monoxide_ug_m3',
 'Nitrogen_Dioxide_ug_m3',
 'Ozone_ug_m3',
 'Dust_ug_m3',
 'UV_Index',
 'European_AQI',
 'Hazardous_Event']

In [10]:
data.dtypes

Timestamp                     str
City                          str
Latitude                  float64
Longitude                 float64
PM10_ug_m3                float64
PM2_5_ug_m3               float64
Carbon_Monoxide_ug_m3     float64
Nitrogen_Dioxide_ug_m3    float64
Ozone_ug_m3               float64
Dust_ug_m3                float64
UV_Index                  float64
European_AQI                int64
Hazardous_Event             int64
dtype: object

## What was learned from Lab 1

The dataset was loaded from `Datasets/Global Urban Air Quality & Pollution Time-Series/global_urban_smog_pm25_hourly.csv` using pandas. At this stage we only confirm that the file can be read and that the dataframe structure is visible. Data cleaning, preprocessing, and modelling are intentionally left for later labs.